package com.oranbyte.screenrec.share.localsend;

import java.security.KeyStore;

/**
 * Holds this device's LocalSend identity: display metadata (alias, model,
 * type, protocol version) plus the fingerprint and keystore used for mutual
 * TLS.
 *
 * <p>The actual certificate/keystore is owned and generated by
 * {@link LocalSendSslContext} — this class only exposes it under the names
 * the rest of the LocalSend code expects. Previously this class generated
 * its own separate keystore at the same file path as
 * {@code LocalSendSslContext}, with a different password/alias; whichever
 * class ran first would win and the other would fail to open the file
 * ("keystore password was incorrect"). Delegating avoids that entirely by
 * ensuring there is exactly one keystore and one owner.
 */
public final class LocalSendIdentity {

	private static final String ALIAS = "ScreenRecorder";
	private static final String DEVICE_MODEL = "Windows";
	private static final String DEVICE_TYPE = LocalSendProtocol.DEVICE_TYPE_DESKTOP;

	private LocalSendIdentity() {
	}

	/**
	 * Returns the SHA-256 fingerprint (lowercase hex) of this device's
	 * client certificate, as generated/persisted by
	 * {@link LocalSendSslContext}.
	 */
	public static String getFingerprint() {
		try {
			return LocalSendSslContext.getCertificateFingerprint();
		} catch (Exception e) {
			throw new IllegalStateException("Unable to compute LocalSend fingerprint.", e);
		}
	}

	/**
	 * Returns the {@link KeyStore} containing this device's private key and
	 * self-signed certificate, for use as the client identity in mutual TLS.
	 */
	public static KeyStore getKeyStore() {
		try {
			return LocalSendSslContext.getKeyStore();
		} catch (Exception e) {
			throw new IllegalStateException("Unable to load LocalSend identity keystore.", e);
		}
	}

	/** Password used to protect the private key entry inside {@link #getKeyStore()}. */
	public static char[] getKeyStorePassword() {
		return LocalSendSslContext.getPassword();
	}

	/** Alias of the private key / certificate entry inside {@link #getKeyStore()}. */
	public static String getKeyAlias() {
		return LocalSendSslContext.getKeyAlias();
	}

	public static String getAlias() {
		return ALIAS;
	}

	public static String getDeviceModel() {
		return DEVICE_MODEL;
	}

	public static String getDeviceType() {
		return DEVICE_TYPE;
	}

	public static String getVersion() {
		return LocalSendProtocol.VERSION;
	}
}